# Naïve Bayes Classifier

---

Alejandro Jesús Manotas Marmolejo

Código: 200108289

In [1]:
#Imports
import pandas as pd

#Import Gaussian Naive Bayes model and Multinomial Naive Bayes model
from sklearn.naive_bayes import GaussianNB, MultinomialNB

#Metrics
from sklearn.metrics import precision_score
from sklearn.model_selection import train_test_split

In [3]:
reviews1 = pd.read_excel('List1.xlsx')
reviews1.head()

   I  Loved  The  Movie  Hated  ...  With  Very  Disgusting  Disappointing  type
0  1      1    1      1      0  ...     0     0           0              0     0
1  1      0    1      1      1  ...     0     0           0              0     1
2  1      0    1      1      0  ...     0     0           0              0     1
3  1      0    1      1      0  ...     0     0           0              0     0
4  0      0    0      1      0  ...     0     0           0              0     0

[5 rows x 26 columns]

In [4]:
reviews2 = pd.read_excel('List2.xlsx')
reviews2.head()

   I  Loved  The  Movie  Hated  Did  ...  Lost  My  Time  No  Comments  type
0  1      1    1      1      0    0  ...     0   0     0   0         0     0
1  1      0    1      1      1    0  ...     0   0     0   0         0     1
2  1      0    1      1      0    1  ...     0   0     0   0         0     1
3  1      0    1      1      0    1  ...     0   0     0   0         0     0
4  0      0    0      1      0    0  ...     0   0     0   0         0     0

[5 rows x 42 columns]

In [88]:
#Gaussian models
gaussian = GaussianNB()
gaussian2 = GaussianNB()

#Multinomial models
multinomial = MultinomialNB()
multinomial2 = MultinomialNB()

#Split features from outputs (List1)
words = reviews1.drop(columns=['type'],axis=1)
r = reviews1['type']

#Split features from outputs (List2)
words2 = reviews2.drop(columns=['type'],axis=1)
r2 = reviews2['type']

#Split the dataset into train and test data (List1)
words_train, words_test, r_train, r_test = train_test_split(words, r , test_size=0.2, random_state=42)

#Split the dataset into train and test data (List2)
words2_train, words2_test, r2_train, r2_test = train_test_split(words2, r2 , test_size=0.2, random_state=420)

#Training Gaussian models
gaussian.fit(words_train,r_train) #List1
gaussian2.fit(words2_train,r2_train) #List2

#Training Multinomial models
multinomial.fit(words_train,r_train) #List1
multinomial2.fit(words2_train,r2_train) #List2

#Predict Gaussian model
r_pred = gaussian.predict(words_test) #List1
r2_pred = gaussian2.predict(words2_test) #List2

#Predict multinomial model
r3_pred = multinomial.predict(words_test) #List1
r4_pred = multinomial2.predict(words2_test) #List2

## Gaussian Model Precision

---

In [89]:
#Precision Gaussian model
print('Precisión 1ra lista:', precision_score(r_test,r_pred , average='micro'))
print('Precisión 2da lista:', precision_score(r2_test,r2_pred , average='micro'))

Precisión 1ra lista: 0.3333333333333333
Precisión 2da lista: 0.5

## Multinomial Model Precision

---

In [90]:
#Precision multinomial model
print("Precisión 1ra lista:", precision_score(r_test,r3_pred , average='micro'))
print("Precisión 2da lista:", precision_score(r2_test,r4_pred , average='micro'))

Precisión 1ra lista: 0.3333333333333333
Precisión 2da lista: 0.6666666666666666

## Conclusión

---

En ambos casos se puede apreciar que la precisión de la 2da lista utilizando tanto el modelo Gaussiano como el modelo multinomial tiene una mayor precisión que la 1ra lista, esto podría deberse gracias a que la 2da lista posee una mayor cantidad de datos que la 1ra lista. En cuanto a la primera lista en ambos modelos presentan una misma precisión pero difieren en la 2da lista, siendo el modelo multinomial una mayor precisión que el modelo Gaussiano.